version: '3'

services:
  django:
    build: .
    command: gunicorn EnergieAPI.wsgi:application --bind 0.0.0.0:9000 --workers 3
    volumes:
      - .:/app
    ports:
      - "9000:9000"  #%20Map%20port%209000%20from%20the%20container%20to%20host
    environment:
      - DEBUG=0
      - SECRET_KEY=CHANGEME
      - ALLOWED_HOSTS=CHANGEME