# Generated by Django 5.0.1 on 2024-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energieterug',
            name='id',
        ),
        migrations.AlterField(
            model_name='energieterug',
            name='Tijdstip',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
