# Generated by Django 5.0.1 on 2024-07-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_remove_energieterug_id_alter_energieterug_tijdstip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVBestanden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSVBestand', models.FileField(upload_to='CSV/')),
            ],
        ),
    ]
