# Generated by Django 5.0.1 on 2024-07-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_csvbestanden'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaartalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jaartal', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='energieterug',
            options={'verbose_name': 'Teruggeleverd Energie', 'verbose_name_plural': 'Teruggeleverd Energie'},
        ),
        migrations.AddField(
            model_name='energieterug',
            name='Jaartal',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='Data.jaartalmodel'),
        ),
    ]
