# Generated by Django 5.0.1 on 2024-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_jaartalmodel_alter_energieterug_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energieterug',
            name='Jaartal',
            field=models.IntegerField(default=2024),
        ),
        migrations.DeleteModel(
            name='JaartalModel',
        ),
    ]
