# Generated by Django 5.0.1 on 2024-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_alter_energieterug_jaartal_delete_jaartalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='energieterug',
            name='Maand',
            field=models.IntegerField(default=7),
        ),
    ]
