# Generated by Django 5.0.1 on 2024-07-16 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_energieterug_maand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energieterug',
            name='Maand',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
